defmodule Euler do
  use Application

  def start(_type, _args) do
    eul1
    eul2
    eul3
    Eul.Supervisor.start_link [], strategy: :one_for_one
  end

  def eul1 do
    IO.write "eul1: "
    """
    If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
    Find the sum of all the multiples of 3 or 5 below 1000.
    """
    rem3or5? = &(rem(&1, 3) == 0 or rem(&1, 5) ==0)
    1..999 |>
    Enum.map(&(&1)) |>
    Enum.filter(rem3or5?) |>
    #Enum.join(" ") |>
    Enum.sum |>
    IO.puts
  end

  def fib(a, _, 0 ) do
    a
  end

  def fib(a, b, n) do
    fib(b, a+b, n-1)
  end

  def eul2 do
    IO.write "eul2: "
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    """

    IO.puts fib(1,1,10)
  end

  def largest_prime(n, i) do
    cond do
      rem(n,i) == 0 -> largest_prime(n, i+6)
      rem(n, i+2) == 0 -> largest_prime(n, i+6)
    end
    n
  end

  def largest_prime(n) do
    cond do
    n <= 1 -> -1
    n <= 3 -> n
    rem(n, 2) == 0 or rem(n,3) == 0 -> -1
    true -> largest_prime(n, 0)
    end

  end

  def eul3 do
    IO.write "eul3: "
    """
    The prime factors of 13195 are 5, 7, 13 and 29.
    What is the largest prime factor of the number 600851475143 ?
    """
    largest_prime(13195)
  end
end
